### PR TITLE
Fixed #2

### LINKED ISSUE #2: Errors with german Umlaut.
Hi, 

correct is, that: 

```
This is my first post. A Post about words.
```

has **9** Words. But with a german umlaut, the count counts one in addition, eg:

```
Dies ist mein erster Eintrag. Ein Eintrag über Wörter.
```

has **10** Words. 

Something must me wrong in the regex.

### PR DESCRIPTION
**Pull request by petershaw**
German umlaute, like those in "Wörter" are fixed.

### CODE REVIEW

**Comment by lepture** [comment]
Is there any reason that you must change `\u4e00-\u9fff` to upper case?

**Comment by petershaw** [comment]
no. sorry - just a editor macro. 
Importent is that every letter is matched. even the ö. Some questions: why is a word not alwasy a printable character, but not the dash? Is splitting on ws not a better solution?

**Comment by lepture** [comment]
@petershaw In CJK, words are not split by whitespace. For example:

> 中文裏這是八個字

It has 8 words.

**Comment by lepture** [comment]
@petershaw could you add a test case for German?

**Pull request merged**
